version: "3.8"

services:
  # Online Course Service
  online-course:
    build: .
    image: online-course:1.0.0
    container_name: online-course
    restart: unless-stopped
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
      # Mount public directory agar Nginx bisa akses file build
      - public_volume:/var/www/html/public
    depends_on:
      - mysql
    networks:
      - online-course-network

  # Nginx Web Server for Online Course
  nginx-online-course:
    image: nginx:alpine
    container_name: nginx-online-course
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/html/storage
      # Mount public directory yang sama dengan PHP container
      - public_volume:/var/www/html/public
    depends_on:
      - online-course
    networks:
      - online-course-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: online_course
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - online-course-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - online-course-network

networks:
  online-course-network:
    driver: bridge

volumes:
  dbdata:
  public_volume:  # Volume untuk sharing public directory
